server:
  port: 8902
spring:
  application:
    name: FeignClient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  httpclient: true
  hystrix:
    enabled: true